### ISSUE TITLE
Typo 'dayly' in chart heading

### ISSUE THREAD

**Issue by hughbris** [wernerjoss/grav-plugin-ipcount#4]
The chart contains a heading 'Dayly Visitors Count for …". Should be "Daily". I'm not sure where to change that, so just adding as an issue for you here.

Ideally, as per translations added if you merge #3 , this will be implemented as translatable text.

**Comment by wernerjoss** [comment]
thanks for the hint, you are right, of course.
I'll take a closer look at your suggestions.

**Comment by wernerjoss** [comment]
done - implemented as translatable text.
